services:
  - type: web
    name: elena-manicure
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_TELEGRAM_BOT_TOKEN
        sync: false
      - key: VITE_TELEGRAM_CHAT_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

